### PR TITLE
fix: Move majority of README contents to wiki

### PR DESCRIPTION
**Pull request by cameronwaterman**
https://ni.visualstudio.com/DefaultCollection/DevCentral/_workitems/edit/1918785

### CODE REVIEW

**Review by mure — APPROVED** [review]
Make sure you prefix the merged commit name with 'fix: '
to trigger a new release

I need to add this documentation to the wiki 😅

**Comment by cameronwaterman** [comment]
> Make sure you prefix the merged commit name with 'fix: ' to trigger a new release
> 
> I need to add this documentation to the wiki 😅

I figure there are several other bugs we need to fix in this repo anyways, and since the upgrade process is manual right now we can probably just wait off on generating a new release.

**Comment by cameronwaterman** [comment]
@mure - Do you think we should add a link to the README that links to the wiki? That should be fine to go in the public help documentation I imagine.

Something like, "For information on contributing to this plugin, please see the [Wiki](https://github.com/ni/systemlink-notebook-datasource/wiki/Getting-Started)"

**Comment by mure** [comment]
@cameronwaterman
I think that's a good idea.

**Pull request merged**
